// <auto-generated />
using System;
using ConversorFaturas.Repository.Configurations.Db;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ConversorFaturas.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20240311203536_Novo1")]
    partial class Novo1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseSerialColumns(modelBuilder);

            modelBuilder.Entity("ConversorFaturas.Domain.Faturas.Fatura", b =>
                {
                    b.Property<int>("Codigo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("CodigoFatura");

                    NpgsqlPropertyBuilderExtensions.UseSerialColumn(b.Property<int>("Codigo"));

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("CATEGORIA");

                    b.Property<int>("CodigoFaturaMesAno")
                        .HasColumnType("INT")
                        .HasColumnName("CODIGOFATURAMESANO");

                    b.Property<DateTime>("Data")
                        .HasColumnType("DATE")
                        .HasColumnName("DATA");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("DESCRICAO");

                    b.Property<decimal>("Valor")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("VALOR");

                    b.HasKey("Codigo");

                    b.HasIndex("CodigoFaturaMesAno");

                    b.ToTable("FATURA", (string)null);
                });

            modelBuilder.Entity("ConversorFaturas.Domain.Faturas.MesAno.FaturaMesAno", b =>
                {
                    b.Property<int>("Codigo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("CodigoFaturaMesAno");

                    NpgsqlPropertyBuilderExtensions.UseSerialColumn(b.Property<int>("Codigo"));

                    b.Property<string>("MesAno")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("MesAno");

                    b.HasKey("Codigo");

                    b.ToTable("FATURAMESANO", (string)null);
                });

            modelBuilder.Entity("ConversorFaturas.Domain.Faturas.Fatura", b =>
                {
                    b.HasOne("ConversorFaturas.Domain.Faturas.MesAno.FaturaMesAno", "FaturaMesAno")
                        .WithMany("Faturas")
                        .HasForeignKey("CodigoFaturaMesAno")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FaturaMesAno");
                });

            modelBuilder.Entity("ConversorFaturas.Domain.Faturas.MesAno.FaturaMesAno", b =>
                {
                    b.Navigation("Faturas");
                });
#pragma warning restore 612, 618
        }
    }
}
