// <auto-generated />
using System;
using Financeiro.Repository.Configurations.Db;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Financeiro.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20240319122915_Extratos")]
    partial class Extratos
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseSerialColumns(modelBuilder);

            modelBuilder.Entity("Financeiro.Domain.ContasMensais.ContaMensal", b =>
                {
                    b.Property<int>("Codigo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("CODIGOCONTAMENSAL");

                    NpgsqlPropertyBuilderExtensions.UseSerialColumn(b.Property<int>("Codigo"));

                    b.Property<DateTime>("Data")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("DESCRICAO");

                    b.Property<string>("MesAnoConta")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("NumeroParcela")
                        .HasColumnType("integer");

                    b.Property<decimal>("Valor")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("VALOR");

                    b.HasKey("Codigo");

                    b.ToTable("CONTAMENSAL", (string)null);
                });

            modelBuilder.Entity("Financeiro.Domain.Extratos.Extrato", b =>
                {
                    b.Property<int>("Codigo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("CodigoExtrato");

                    NpgsqlPropertyBuilderExtensions.UseSerialColumn(b.Property<int>("Codigo"));

                    b.Property<int>("CodigoExtratoMesAno")
                        .HasColumnType("INT")
                        .HasColumnName("CODIGOEXTRATOMESANO");

                    b.Property<DateTime>("Data")
                        .HasColumnType("DATE")
                        .HasColumnName("DATA");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("DESCRICAO");

                    b.Property<Guid>("Identificador")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Valor")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("VALOR");

                    b.HasKey("Codigo");

                    b.HasIndex("CodigoExtratoMesAno");

                    b.ToTable("EXTRATO", (string)null);
                });

            modelBuilder.Entity("Financeiro.Domain.Extratos.MesAno.ExtratoMesAno", b =>
                {
                    b.Property<int>("Codigo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("CodigoExtratoMesAno");

                    NpgsqlPropertyBuilderExtensions.UseSerialColumn(b.Property<int>("Codigo"));

                    b.Property<string>("MesAno")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("MesAno");

                    b.HasKey("Codigo");

                    b.ToTable("EXTRATOMESANO", (string)null);
                });

            modelBuilder.Entity("Financeiro.Domain.Faturas.Fatura", b =>
                {
                    b.Property<int>("Codigo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("CodigoFatura");

                    NpgsqlPropertyBuilderExtensions.UseSerialColumn(b.Property<int>("Codigo"));

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("CATEGORIA");

                    b.Property<int>("CodigoFaturaMesAno")
                        .HasColumnType("INT")
                        .HasColumnName("CODIGOFATURAMESANO");

                    b.Property<DateTime>("Data")
                        .HasColumnType("DATE")
                        .HasColumnName("DATA");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("DESCRICAO");

                    b.Property<decimal>("Valor")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("VALOR");

                    b.HasKey("Codigo");

                    b.HasIndex("CodigoFaturaMesAno");

                    b.ToTable("FATURA", (string)null);
                });

            modelBuilder.Entity("Financeiro.Domain.Faturas.MesAno.FaturaMesAno", b =>
                {
                    b.Property<int>("Codigo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("CodigoFaturaMesAno");

                    NpgsqlPropertyBuilderExtensions.UseSerialColumn(b.Property<int>("Codigo"));

                    b.Property<string>("MesAno")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("MesAno");

                    b.HasKey("Codigo");

                    b.ToTable("FATURAMESANO", (string)null);
                });

            modelBuilder.Entity("Financeiro.Domain.Extratos.Extrato", b =>
                {
                    b.HasOne("Financeiro.Domain.Extratos.MesAno.ExtratoMesAno", "ExtratoMesAno")
                        .WithMany("Extratos")
                        .HasForeignKey("CodigoExtratoMesAno")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ExtratoMesAno");
                });

            modelBuilder.Entity("Financeiro.Domain.Faturas.Fatura", b =>
                {
                    b.HasOne("Financeiro.Domain.Faturas.MesAno.FaturaMesAno", "FaturaMesAno")
                        .WithMany("Faturas")
                        .HasForeignKey("CodigoFaturaMesAno")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FaturaMesAno");
                });

            modelBuilder.Entity("Financeiro.Domain.Extratos.MesAno.ExtratoMesAno", b =>
                {
                    b.Navigation("Extratos");
                });

            modelBuilder.Entity("Financeiro.Domain.Faturas.MesAno.FaturaMesAno", b =>
                {
                    b.Navigation("Faturas");
                });
#pragma warning restore 612, 618
        }
    }
}
